/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualIndexRouteImport } from './routes/visual/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevJsonFormatterRouteImport } from './routes/dev/json-formatter'
import { Route as DevJsonEditorRouteImport } from './routes/dev/json-editor'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualIndexRoute = VisualIndexRouteImport.update({
  id: '/visual/',
  path: '/visual/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevJsonFormatterRoute = DevJsonFormatterRouteImport.update({
  id: '/dev/json-formatter',
  path: '/dev/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const DevJsonEditorRoute = DevJsonEditorRouteImport.update({
  id: '/dev/json-editor',
  path: '/dev/json-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dev/json-editor': typeof DevJsonEditorRoute
  '/dev/json-formatter': typeof DevJsonFormatterRoute
  '/dev': typeof DevIndexRoute
  '/visual': typeof VisualIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dev/json-editor': typeof DevJsonEditorRoute
  '/dev/json-formatter': typeof DevJsonFormatterRoute
  '/dev': typeof DevIndexRoute
  '/visual': typeof VisualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dev/json-editor': typeof DevJsonEditorRoute
  '/dev/json-formatter': typeof DevJsonFormatterRoute
  '/dev/': typeof DevIndexRoute
  '/visual/': typeof VisualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/dev/json-editor'
    | '/dev/json-formatter'
    | '/dev'
    | '/visual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/dev/json-editor'
    | '/dev/json-formatter'
    | '/dev'
    | '/visual'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/dev/json-editor'
    | '/dev/json-formatter'
    | '/dev/'
    | '/visual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DevJsonEditorRoute: typeof DevJsonEditorRoute
  DevJsonFormatterRoute: typeof DevJsonFormatterRoute
  DevIndexRoute: typeof DevIndexRoute
  VisualIndexRoute: typeof VisualIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual/': {
      id: '/visual/'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof VisualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/json-formatter': {
      id: '/dev/json-formatter'
      path: '/dev/json-formatter'
      fullPath: '/dev/json-formatter'
      preLoaderRoute: typeof DevJsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/json-editor': {
      id: '/dev/json-editor'
      path: '/dev/json-editor'
      fullPath: '/dev/json-editor'
      preLoaderRoute: typeof DevJsonEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DevJsonEditorRoute: DevJsonEditorRoute,
  DevJsonFormatterRoute: DevJsonFormatterRoute,
  DevIndexRoute: DevIndexRoute,
  VisualIndexRoute: VisualIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
